export const optionsSorted = [
  { name: "Alphabetical sort: A - Z", id: "A-Z" },
  { name: "Alphabetical sort: Z - A", id: "Z-A" },
  { name: "Weight sort: min - max", id: "Min-Max_weight" },
  { name: "Weight sort: max - min", id: "Max-Min_weight" },
  { name: "Attack power: min - max", id: "Min-Max_attack" },
  { name: "Attack power: max - min", id: "Max-Min_attack" },
];

export const optionsType = [
  { id: 1, name: "poison" },
  { id: 3, name: "fighting" },
  { id: 2, name: "flying" },
  { id: 4, name: "normal" },
  { id: 5, name: "ground" },
  { id: 6, name: "rock" },
  { id: 7, name: "bug" },
  { id: 8, name: "ghost" },
  { id: 9, name: "steel" },
  { id: 10, name: "fire" },
  { id: 11, name: "water" },
  { id: 12, name: "grass" },
  { id: 13, name: "electric" },
  { id: 14, name: "psychic" },
  { id: 15, name: "ice" },
  { id: 16, name: "dragon" },
  { id: 17, name: "dark" },
  { id: 18, name: "fairy" },
  { id: 19, name: "unknown" },
  { id: 20, name: "shadow" },
];
